name: Github Action Demo
description: A Github Action fro Python Language
inputs:
  valor:
    descripts: Ingrese un valor
    required: true
outputs:
  result:
    description: Mostrar un saludo con el nombre ingresado
    value: ${{steps.get-results.outputs.result}}

runs:
  using: composite 
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Pass Inputs to Shell
      run: |
        echo "INPUT_VAL=${{inputs.valor}}" >>$GITHUB_ENV
      shell: bash
    - name: Get result
      id: get-results
      run: python src/main
      shell: bash
